// <auto-generated />
using AWEPP.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AWEPP.Migrations
{
    [DbContext(typeof(Aweppcontext))]
    [Migration("20240925163401_initial")]
    partial class Anitial : initialBase
    {
    }
}
